    name: "Bakuchiol Serum",
    brand: "Sephora",
    price: "$64.60",
    originalPrice: "$68.00",
    badge: "5% OFF",
    desc: "Natural retinol alternative. Trending r/SkincareAddiction.",
    url: "https://www.sephora.com/search?keyword=bakuchiol",
    avatar: "https://d2xsxph8kpxj0f.cloudfront.net/310519663435070666/UKZTwoEXuGkRzDU2B5gMpQ/avatar_la_hollywood_fbc34862.png",
    avatarName: "The Starlet · Hollywood",