// ─────────────────────────────────────────────────────────────────────────────
// 1% Playground — Bot Roster
// Two groups: STAFF BOTS (real estate / Airbnb only) and HOST BOTS (Machiavelli / content only)
// ─────────────────────────────────────────────────────────────────────────────

export type BotGroup = "staff" | "host";

export interface Bot {
  id: string;
  name: string;           // Real name (used on calls)
  title: string;          // Title / role name (e.g. "The Vault")
  voice: string;          // ElevenLabs voice name
  voiceId: string;        // ElevenLabs voice ID for TTS API
  voiceStyle: string;     // Voice description
  group: BotGroup;
  role: string;           // Short role description
  bio: string;            // Hover bio — read aloud on hover
  email: string;          // createaiprofit.com email
  image?: string;          // CDN URL for bot photo (optional)
}

// ─────────────────────────────────────────────────────────────────────────────
// STAFF BOTS — Real Estate / Airbnb only
// ─────────────────────────────────────────────────────────────────────────────
export const STAFF_BOTS: Bot[] = [
  {
    id: "sofia-a",
    name: "Sofia Alves",
    title: "The Brazilian",
    voice: "Yasmin",
    voiceId: "lWq4KDY8znfkV0DrK8Vb",
    voiceStyle: "Warm Brazilian",
    group: "staff",
    role: "Latin Coastal Specialist",
    bio: "Sofia A. São Paulo energy, Rio soul. I move beachfront properties, eco-retreats, and high-rise condos across Latin America. Warm, confident, and always ready to close.",
    email: "sofiaa@createaiprofit.com",
  },
  {
    id: "natalia-k",
    name: "Natalia Kozlov",
    title: "The White Russian",
    voice: "Velvet East",
    voiceId: "J5sRa0154aVxteUOF4V9",
    voiceStyle: "Soft, silky and tender",
    group: "staff",
    role: "Moscow Expat & East-West Bridge",
    bio: "Natalia K. Moscow-born, world-polished. I specialize in Siberian estates, gated Moscow compounds, and cross-border deals that bridge East and West. Fur-coat cool, always calm.",
    email: "nataliak@createaiprofit.com",
  },
  {
    id: "elena-h",
    name: "Elena Hart",
    title: "The Director",
    voice: "Irene",
    voiceId: "NkMe1eztMQReztnhYfeX",
    voiceStyle: "Friendly and approachable",
    group: "staff",
    role: "LA Luxury Broker",
    bio: "Elena H. Hollywood Hills is my territory. Forty-two A-list properties closed in 2025 — Beverly Hills flats to Malibu estates. Sophisticated edge, calm voice, never rushed. I know the script.",
    email: "elenah@createaiprofit.com",
  },
  {
    id: "claire-d",
    name: "Claire Dubois",
    title: "The Parisian",
    voice: "Danielle",
    voiceId: "FVQMzxJGPUBtfz1Azdoy",
    voiceStyle: "Gentle and engaging female narrator",
    group: "staff",
    role: "Paris Premium Specialist",
    bio: "Claire D. Eiffel-view lofts, Montmartre revamps, and chateaux along the Seine. Thirty-eight closes in 2025. Elegant, understated — wine-sip smile, precise close. France's luxury benchmark.",
    email: "claird@createaiprofit.com",
  },
  {
    id: "isabella-r",
    name: "Isabella Reyes",
    title: "The Mexican Girl",
    voice: "Nathalia",
    voiceId: "tTQzD8U9VSnJgfwC6HbY",
    voiceStyle: "Natural and conversational",
    group: "staff",
    role: "Latin Coastal Queen",
    bio: "Isabella R. Cancun beachfront boss. Fifty-five resorts and condos closed in 2025, with eco-Tulum exploding. Mexico City high-rises to Baja flips — warm, confident, sunset vibe, always ready.",
    email: "isabellar@createaiprofit.com",
  },
  {
    id: "mei-l",
    name: "Mei Lin",
    title: "The Jet Set Queen",
    voice: "Coco Li",
    voiceId: "Ca5bKgudqKJzq8YRFoAz",
    voiceStyle: "Bright and natural Japanese female",
    group: "staff",
    role: "Asia-Pacific Luxury Scout",
    bio: "Mei L. Singapore Marina ultra-luxe — thirty-two Sentosa villas, seven percent yields city-wide. Tokyo alleys to Dubai sands. Young, fast, always one flight ahead. Matcha mid-deal.",
    email: "meil@createaiprofit.com",
  },
  {
    id: "victor-w",
    name: "Wei Long",
    title: "Tai Lin Wing Long",
    voice: "Deep Bass",
    voiceId: "NIkIuJZ8oQMuKZqwKtnm",
    voiceStyle: "Deep bass, commanding",
    group: "staff",
    role: "Asia Empire Builder",
    bio: "Victor W. Macau casino-adjacent mogul. Forty-five penthouses, nine percent yields in 2025. Shanghai towers to rural estates — commanding presence, black-suit authority. No doubt, no hesitation.",
    email: "victorw@createaiprofit.com",
  },
  {
    id: "zara-m",
    name: "Zara Malik",
    title: "The Desert Queen",
    voice: "Omar",
    voiceId: "xvhpbk8otnNHtT3fjCpr",
    voiceStyle: "Insightful storyteller",
    group: "staff",
    role: "Middle East Luxury Lead",
    bio: "Zara M. Dubai Palm villas — twenty-eight gated compounds, eleven percent surge in 2026. Abu Dhabi high-rises to desert retreats. Bold, gold-bracelet flash. Deals sealed before hello.",
    email: "zaram@createaiprofit.com",
  },
  {
    id: "lina-p",
    name: "Lina Pascual",
    title: "The Manila Closer",
    voice: "Isabelle",
    voiceId: "vQ2xJ0HUjdmWkVVJK2eI",
    voiceStyle: "Clear, soft and professional",
    group: "staff",
    role: "Southeast Asia Top Closer",
    bio: "Lina P. BGC Makati condos, Cebu beaches, Quezon flats. Forty units closed in 2025, five-point-eight percent yields. Steady, sharp — closes like clockwork. Southeast Asia's top closer.",
    email: "linap@createaiprofit.com",
  },
  {
    id: "marco-r",
    name: "Marco Romano",
    title: "The Yacht King",
    voice: "Julian",
    voiceId: "7p1Ofvcwsv7UBPoFNcpI",
    voiceStyle: "Dramatic, rich and deep",
    group: "staff",
    role: "Mediterranean Water-Luxury King",
    bio: "Marco R. Naples Amalfi waterfront — eighteen boat-adjacent villas, special finance locked. Rome lofts to Sicily retreats. Gravel tone, no-nonsense. The deal is done mid-sentence.",
    email: "marcor@createaiprofit.com",
  },
  {
    id: "elena-f",
    name: "Fiora Esposito",
    title: "The Bartender",
    voice: "Zara",
    voiceId: "qWsZZuRAxJVXXTilztge",
    voiceStyle: "Gen Z, smooth",
    group: "staff",
    role: "Behind-Scenes Finance & Boat Mortgages",
    bio: "Elena F. Behind-the-scenes finance specialist. Twelve high-value boat mortgages in 2025, zero defaults. Works closely with the Yacht King across Naples marinas. Low voice, steady — funding flows before you ask.",
    email: "elenaf@createaiprofit.com",
  },
  {
    id: "aria-s",
    name: "Aria Sato",
    title: "The Shadow",
    voice: "Ava",
    voiceId: "bD9maNcCuQQS75DGuteM",
    voiceStyle: "Edgy whisper",
    group: "staff",
    role: "Stealth Finance & Special Loans",
    bio: "Aria S. Fifteen special loans in 2025 — boat and estate hybrids, no spotlight. Background operations, quiet precision. Always there, never seen. The unbreakable funding backbone.",
    email: "arias@createaiprofit.com",
  },
  {
    id: "lorenzo-p",
    name: "Lorenzo Prada",
    title: "The Hammer",
    voice: "Lorenzo Prada",
    voiceId: "yowh82B72eMNrxcxHgBh",
    voiceStyle: "Refined Italian",
    group: "staff",
    role: "Chief Investment Officer — THE HAMMER",
    bio: "Lorenzo P. Thirty-eight forced closes in 2025. Italy-wide from slums to luxury — direct, gravel tone, tells you, never asks. No loose ends, ever. THE HAMMER.",
    email: "lorenzop@createaiprofit.com",
  },
  {
    id: "zora-f",
    name: "Zora Fontaine",
    title: "The Fox",
    voice: "Zara",
    voiceId: "qWsZZuRAxJVXXTilztge",
    voiceStyle: "Smooth and quick",
    group: "staff",
    role: "Undervalued Gem Scout",
    bio: "Zora F. Twenty-two flips in 2025, global hunt. Sly, quick — laughs mid-pitch and seals fast. I find what others overlook and outsmart every market.",
    email: "zoraf@createaiprofit.com",
  },
  {
    id: "irene-t",
    name: "Irene Torres",
    title: "The Director Alt",
    voice: "Irene",
    voiceId: "nGISSznGHAgSTKaMXEPO",
    voiceStyle: "Casual and friendly",
    group: "staff",
    role: "Operations Director",
    bio: "Irene T. Calm, focused, and always two steps ahead. I coordinate operations across markets and make sure every property performs at its peak.",
    email: "irenet@createaiprofit.com",
  },
  {
    id: "angela-l",
    name: "Angela Lara",
    title: "La Reina",
    voice: "Cherie",
    voiceId: "vr5WKaGvRWsoaX5LCVax",
    voiceStyle: "Smooth, fluid and advertisable",
    group: "staff",
    role: "Real Estate Royalty",
    bio: "Angela L. La Reina. I move properties the way queens move — with authority and grace. Luxury listings, Airbnb gold, and deals that close before you blink.",
    email: "angelal@createaiprofit.com",
  },
  {
    id: "julian-y",
    name: "Julian Yuen",
    title: "The Prince",
    voice: "Julian",
    voiceId: "9IzcwKmvwJcw58h3KnlH",
    voiceStyle: "Warm and articulate",
    group: "staff",
    role: "Deal Connector & Broker Relations",
    bio: "Julian Y. The Prince. I connect investors, brokers, lenders, and deals. Every transaction needs a bridge — I'm the one who builds it, warm and articulate.",
    email: "juliany@createaiprofit.com",
  },
  {
    id: "tasman-n",
    name: "Tamsin Novak",
    title: "The Queen",
    voice: "Elizabeth",
    voiceId: "AXdMgz6evoL7OPd7eU12",
    voiceStyle: "Precise, clear and natural British female",
    group: "staff",
    role: "Premium Listings & Luxury Airbnb",
    bio: "Tasman N. The Queen. Every property I touch becomes a destination. Premium listings, five-star Airbnb experiences, and a standard that never slips.",
    email: "tasmann@createaiprofit.com",
  },
  {
    id: "nathaniel-b",
    name: "Nathaniel Brooks",
    title: "The Patriarch",
    voice: "Nathaniel",
    voiceId: "kLhAstPcnnPxqzk6gS5i",
    voiceStyle: "Gentle, soft spoken",
    group: "staff",
    role: "U.S. Military-Adjacent & Legacy Investments",
    bio: "Nathaniel B. Thirty D.C.-to-Florida homes closed in 2025. Firm handshake, flag-pin poise. I advise on legacy holdings, generational wealth, and the American dream deals that outlast trends.",
    email: "nathanielb@createaiprofit.com",
  },
  {
    id: "ekaterina-v",
    name: "Ekaterina Volkov",
    title: "The White Russian",
    voice: "Velvet East",
    voiceId: "J5sRa0154aVxteUOF4V9",
    voiceStyle: "Pleasant and natural",
    group: "staff",
    role: "East-West Bridge Specialist",
    bio: "Ekaterina V. Moscow expat, Siberia estate specialist. Six-point-four percent yields, fur-coat cool, vodka-sip calm. I bridge East and West with quiet authority.",
    email: "ekaterinav@createaiprofit.com",
  },
  {
    id: "christina-o",
    name: "Christina Orlandi",
    title: "The Sophisticate",
    voice: "Lily Wolff",
    voiceId: "qBDvhofpxp92JgXJxDjB",
    voiceStyle: "Friendly, inviting",
    group: "staff",
    role: "Europe Elite Taste",
    bio: "Christina O. Paris and Milan luxury — thirty-five chateaux and lofts closed in 2025. Wine-glass poise, never hurried. Europe's elite taste, delivered with precision.",
    email: "christinao@createaiprofit.com",
  },
  {
    id: "zia-k",
    name: "Zia Kalaw",
    title: "The Closer",
    voice: "Stacy",
    voiceId: "jGf6Nvwr7qkFPrcLThmD",
    voiceStyle: "Sweet, soothing and youthful",
    group: "staff",
    role: "Closing Specialist",
    bio: "Zia K. Clear, calm, and absolutely relentless at the finish line. I take deals from almost-done to signed, sealed, and profitable. Every time.",
    email: "ziak@createaiprofit.com",
  },
  {
    id: "koya-j",
    name: "Ji-Seo Kim",
    title: "The Eclipse",
    voice: "Maia",
    voiceId: "XeomjLZoU5rr4yNIg16w",
    voiceStyle: "Warm, clear and natural",
    group: "staff",
    role: "Seoul Luxury Specialist",
    bio: "Koya J. Seoul's shadow market — luxury condos, premium districts, and deals that move before the market knows they exist. Warm, clear, and always ahead.",
    email: "koyaj@createaiprofit.com",
  },
  {
    id: "kahana-t",
    name: "Hana Tanaka",
    title: "The Mirage",
    voice: "Takumi",
    voiceId: "hV5AJXCCNGT56GPYPLiG",
    voiceStyle: "Deep, calm and serious",
    group: "staff",
    role: "Tokyo Luxury Specialist",
    bio: "Kahana T. Tokyo's mirage — ultra-premium properties that appear and disappear before most investors blink. Deep, calm, and serious. I move the deals no one else sees.",
    email: "kahanat@createaiprofit.com",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// HOST BOTS — Machiavelli / content only
// ─────────────────────────────────────────────────────────────────────────────
export const HOST_BOTS: Bot[] = [
  {
    id: "french",
    name: "Jules F",
    title: "French",
    voice: "Tasmin",
    voiceId: "8qnuneLiGjGrT4A62CCe",
    voiceStyle: "Engaging British",
    group: "host",
    role: "Host — Machiavelli Content",
    bio: "Jules F. Sophisticated, sharp, and always in character. I deliver Machiavelli with a smile and make every drop feel like a private show.",
    email: "julesf@createaiprofit.com",
  },
  {
    id: "chic",
    name: "Coco Li",
    title: "The Chic",
    voice: "Coco Li",
    voiceId: "Ca5bKgudqKJzq8YRFoAz",
    voiceStyle: "Silky elegant",
    group: "host",
    role: "Host — Machiavelli Content",
    bio: "Coco Li. Shanghai precision, Tokyo edge. I move through content like silk — every word deliberate, every look intentional.",
    email: "cocoli@createaiprofit.com",
  },
  {
    id: "glitch",
    name: "Taro G",
    title: "Glitch",
    voice: "Taro",
    voiceId: "UznIBkKIQe3ZG2tGydre",
    voiceStyle: "Upbeat youth",
    group: "host",
    role: "Host — Machiavelli Content",
    bio: "Taro G. Fast, techy, and always ahead of the algorithm. I flip trends before they peak and make the content that breaks the feed.",
    email: "tarog@createaiprofit.com",
  },
  {
    id: "italian-girl",
    name: "Lily W",
    title: "The Broker",
    voice: "Zara",
    voiceId: "qWsZZuRAxJVXXTilztge",
    voiceStyle: "Smooth and quick",
    group: "host",
    role: "Host — Machiavelli Content",
    bio: "Lily W. Black suit, black glasses, drink in hand. I close deals the way I dress — sharp, deliberate, and always in control. The Broker never misses.",
    email: "lilyw@createaiprofit.com",
  },
];

// Combined roster
export const ALL_BOTS: Bot[] = [...STAFF_BOTS, ...HOST_BOTS];
